### ISSUE TITLE
Need user images for README

### ISSUE THREAD

**Issue by trigg** [trigg/DiscordOverlayLinux#11]
Please consider taking a screenshot of this in use and uploading it as an image in this bug report.

Thank you!

**Comment by trigg** [comment]
![Steam Big Picture](https://user-images.githubusercontent.com/535772/81019771-e0ea3b00-8e56-11ea-9afe-7b684478e1de.png)

**Comment by midget3111** [comment]
![Screenshot from 2020-05-03 13-33-25](https://user-images.githubusercontent.com/964775/81019917-99b47800-8e5f-11ea-9514-2b3cef24ebbf.png)

**Comment by Tiixxel** [comment]
![Screenshot from 2020-05-05 20-11-58](https://user-images.githubusercontent.com/42376598/81100934-9ed00080-8f0d-11ea-8ecc-e51d324c7fbd.png)

**Comment by Tiixxel** [comment]
![Screenshot from 2020-05-05 20-20-21](https://user-images.githubusercontent.com/42376598/81101091-e48cc900-8f0d-11ea-872a-c2ee3d16138a.png)

**Comment by timdevorg** [comment]
![Screenshot from 2020-05-05 20-22-25](https://user-images.githubusercontent.com/42376598/81101265-274ea100-8f0e-11ea-83dc-1a5476bffe3d.png)

**Comment by trigg** [comment]
![Screenshot from 2020-05-26 11-53-48](https://user-images.githubusercontent.com/535772/82892575-a2243e00-9f47-11ea-8d42-0ec08be39441.png)

**Comment by xenorio** [comment]
![image](https://user-images.githubusercontent.com/39472201/87666669-516fdb00-c769-11ea-9c00-755ca596c68c.png)
