### ISSUE TITLE
Multi-monitor support

### ISSUE THREAD

**Issue by Nadyita** [trigg/DiscordOverlayLinux#12]
I *love* this overlay, thank you so much for this!
But: I have 2 monitors and I'd like to choose which monitor the overlay goes to. It seems to always pick the primary one, but I usually play on my secondary  :-X

**Comment by trigg** [comment]
Thank you! I had wondered briefly about how this would be handled, I will move monitors about and try to get to the bottom of this!

**Comment by trigg** [comment]
With latest PR I believe this is complete. Any bugs found in Multi-screen can be reported elsewhere
