### ISSUE TITLE
[feature] microphone status

### ISSUE THREAD

**Issue by ZyanKLee** [trigg/DiscordOverlayLinux#13]
hey @trigg, thanks for the work on this nifty little overlay.

If it is technically possible, it would be great if this could include the status of one's own microphone (muted / unmuted)?

**Comment by trigg** [comment]
This one will prove more challenging than others as (I suspect) this info isn't relayed out of Discord at all. I will investigate, none the less!

**Comment by ZyanKLee** [comment]
nice ... 
![Bildschirmfoto von 2020-05-06 18-40-52](https://user-images.githubusercontent.com/1178490/81204205-38a8b380-8fc9-11ea-86bd-c470ceec46e9.png)

thanks for that great work!
