### ISSUE TITLE
[Feature] Automagic Server Change

### ISSUE THREAD

**Issue by midget3111** [trigg/DiscordOverlayLinux#15]
Unsure how tricky this one will be to implement... Ideally the script should detect when a user has left the server to join a new one. 

Desired outcome should either -
A) Ask user if they want to change the script to display their current server,
B) Auto change server and display the users current channel

Personally I think B is preferable

**Comment by trigg** [comment]
Basics of this are here

https://github.com/trigg/DiscordOverlayLinux/wiki/Switching-Views-when-moving-rooms-or-servers
