### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [trigg/DiscordOverlayLinux#29]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Discord Overlay for Linux on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by midget3111** [comment]
Hey, I'm currently looking into the best way to package up and deploy the project. However, before we get to that point we need to implement a proper versioning system and have a stable release :).

**Comment by lineber** [comment]
Is it possible to install it within the Steam Flatpak? Right now, the Discord Flatpak doesn't recognize the Steam games.

flatpak run --command=bash com.valvesoftware.Steam

**Comment by trigg** [comment]
Duplicate of #16
