### ISSUE TITLE
Debian Gnome Wayland: No input except Overlay App

### ISSUE THREAD

**Issue by timdevorg** [trigg/DiscordOverlayLinux#3]
After installing some Qt5 dependencies and changing the first line of the script, it does works now. But it doesn't let me press anything in Discord, Firefox etc. I can only interact with the Overlay App which is quite annoying. (Debian testing, Gnome Wayland)

**Comment by MCOfficer** [comment]
i might be wrong, but is python2 still the default on debian?
https://github.com/trigg/DiscordOverlayLinux/blob/dcc72c506d6762ec0a2b2ee3d26314b606b5911e/overlay-qt5.py#L1

If yes, you need to change this to `#!/usr/bin/python3`.

**Comment by trigg** [comment]
I've commited 6f7ccd5, to change the first line as per @MCOfficer 's advice.

Thanks both!

**Comment by Tiixxel** [comment]
After installing some Qt5 dependencies, it works now. But it doesn't let me press anything in Discord, Firefox etc. I can only interact with the Overlay App which is quite annoying. (Debian testing, Gnome Wayland)

**Comment by trigg** [comment]
That's fair. Can you check if Gnome on X11 does the same, as I suspect it's QT on wayland that would cause this. If it happens the same on Gnome/X11 in your circumstances then we've got a problem in this code.

Also please don't edit bug reports for a totally unrelated bug, as it doesn't notify me and will get lost in the ether.

**Comment by timdevorg** [comment]
One odd thing is, that I have no mouse / keyboard input under X11 (just tried it out). Never had these issues before when I used X11 daily. I'll try to get this working, can't make any promises.

**Comment by timdevorg** [comment]
It does fully and correctly work on X11. Seems like that is a Problem with XWayland.

**Comment by trigg** [comment]
It's more likely Gnome+Wayland specific, as Wayfire worked right away. None the less I'm leaving this open as I hope to either fix all Wayland before long or fork the project for a wayland specific version

**Comment by timdevorg** [comment]
Seems like this issue is fixed in Fedora, I can use the Overlay on Gnome with Wayland without any problems.

**Comment by timdevorg** [comment]
I just updated my System and the Overlay works now without any issues on Debian Gnome with Wayland.
