### ISSUE TITLE
Application does not run

### ISSUE THREAD

**Issue by AdalynBlack** [trigg/DiscordOverlayLinux#33]
I am using Xfce4 for my desktop environment running on ArchLinux. I installed this through the AUR, and when I run it, it gives me a single error, creates an icon on the top right, and then execution appears to stop. Trying to force it to stop does nothing, and I have to manually close it with something like htop for it to close.

`WARNING  Chose screen 'HDMI2' as fallback because 'None'`

**Comment by stepanse** [comment]
I would like to repport that the same happens on Arch with Cinnamon. Here is the complete log
```[stepan@destr01 ~]$ discord-overlay

(python3:13628): Gtk-WARNING **: 11:59:13.701: Nelze nalézt systém motivů v module_path: "murrine",

(python3:13628): Gtk-WARNING **: 11:59:13.702: Nelze nalézt systém motivů v module_path: "murrine",

(python3:13628): Gtk-WARNING **: 11:59:13.702: Nelze nalézt systém motivů v module_path: "murrine",

(python3:13628): Gtk-WARNING **: 11:59:13.702: Nelze nalézt systém motivů v module_path: "murrine",

(python3:13628): Gtk-WARNING **: 11:59:13.702: Nelze nalézt systém motivů v module_path: "murrine",

(python3:13628): Gtk-WARNING **: 11:59:13.702: Nelze nalézt systém motivů v module_path: "murrine",

(python3:13628): Gtk-WARNING **: 11:59:13.702: Nelze nalézt systém motivů v module_path: "murrine",

(python3:13628): Gtk-WARNING **: 11:59:13.703: Nelze nalézt systém motivů v module_path: "murrine",

(python3:13628): Gtk-WARNING **: 11:59:13.703: Nelze nalézt systém motivů v module_path: "murrine",

(python3:13628): Gtk-WARNING **: 11:59:13.703: Nelze nalézt systém motivů v module_path: "murrine",

(python3:13628): Gtk-WARNING **: 11:59:13.703: Nelze nalézt systém motivů v module_path: "murrine",
2020-05-26 11:59:13,798 WARNING  Chose screen 'HDMI-A-0' as fallback because 'None' could not be matched```

**Comment by trigg** [comment]
No errors that I see here, Just a warning and some theme errors (how do you get a gtk error in a qt app?) 

Check you've set up an overlay by right clicking the icon and configuring the layout + position of the overlay.

If that fails attach you config files at ~/.config/discord-overlay/discoverlay.ini

**Comment by stepanse** [comment]
I have zero idea about the GTK errors.
Secondly, I'm sorry the icon was just invisible on the taskbar. Sorry guys.

**Comment by trigg** [comment]
Nothing to be sorry for. Does your panel have a system-tray widget? All control is done via a system tray in the current implementation

**Comment by AdalynBlack** [comment]
All that I get is that warning and a new icon on the system tray, nothing else happens.

![image](https://user-images.githubusercontent.com/32852821/82944880-d8b28680-9f50-11ea-90a3-b57fa32fe613.png)

**Comment by trigg** [comment]
Did you try right clicking it?

**Comment by AdalynBlack** [comment]
that works, I could have sworn I tried that, but I guess not. Thanks!
