### ISSUE TITLE
Editing layout changes setting for all voice channels

### ISSUE THREAD

**Issue by midget3111** [trigg/DiscordOverlayLinux#37]
When changing channel settings in the Layout option for one overlay, it changes the channel for other overlays as well.

**Comment by Himes0-0** [comment]
I'm having the same issue that you're having and its also causing me to only have one channel on at a time

**Comment by midget3111** [comment]
I believe this might now be fixed thanks to https://github.com/trigg/DiscordOverlayLinux/commit/4a4e69d40ef48b62d2abc5dcc4ce3c42fb243539, could you test the latest version @Himes0-0 ?
