### ISSUE TITLE
Automatically detect when you join a VC

### ISSUE THREAD

**Issue by Novantric** [trigg/DiscordOverlayLinux#40]
Hi,
This seems to be a super useful app, but aside from the fact I can't move it to the very top left of my screen I have to manually choose which VC to join for the overlay to appear. It would be useful if the overlay just appeared for all VC's when you join them.
thanks

**Comment by trigg** [comment]
I can only work with the information already provided by StreamKit for Discord, as such I wrote a generalised how-to for exactly this use-case

https://github.com/trigg/DiscordOverlayLinux/wiki/Switching-Views-when-moving-rooms-or-servers
