### ISSUE TITLE
Easy way to terminate the script

### ISSUE THREAD

**Issue by xenorio** [trigg/DiscordOverlayLinux#43]
Currently, the only way of closing the overlay i can see is killing the process via terminal. 

Something like a dedicated keybind would be way better.

**Comment by trigg** [comment]
Overlay Settings & Exit are available through the system tray. The icon is a circle.

**Comment by xenorio** [comment]
oh, well, i don't have a system tray, so i guess that explains why i didn't find anything. sorry about that.
