### ISSUE TITLE
Run Failure on Ubuntu 20.04

### ISSUE THREAD

**Issue by dsk0** [trigg/DiscordOverlayLinux#45]
Hi there

Having trouble running this on Ubuntu 20.04.1. 

Running:
<pre>
~/.local/bin$ ./discord-overlay 
Traceback (most recent call last):
  File "./discord-overlay", line 5, in <module>
    from discord_overlay.discord_overlay import entrypoint
  File "/home/master/.local/lib/python3.8/site-packages/discord_overlay/__init__.py", line 1, in <module>
    from .discord_overlay import *
  File "/home/master/.local/lib/python3.8/site-packages/discord_overlay/discord_overlay.py", line 21, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
</pre>

First time I installed there was something about incompatible pyqt versions:
<pre>
$python -m pip install .
Processing /home/master/Programs/DiscordOverlayLinux
Requirement already satisfied: PyQt5 in /usr/lib/python3/dist-packages (from discordoverlaylinux==0.0.1) (5.14.1)
Collecting PyQt5-sip
  Downloading PyQt5_sip-12.8.0-cp38-cp38-manylinux1_x86_64.whl (293 kB)
     |████████████████████████████████| 293 kB 1.3 MB/s 
Collecting PyQtWebEngine
  Downloading PyQtWebEngine-5.15.0-5.15.0-cp35.cp36.cp37.cp38-abi3-manylinux2014_x86_64.whl (65.9 MB)
     |████████████████████████████████| 65.9 MB 9.5 MB/s 
Collecting pyxdg
  Downloading pyxdg-0.26-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 3.4 MB/s 
Building wheels for collected packages: discordoverlaylinux
  Building wheel for discordoverlaylinux (setup.py) ... done
  Created wheel for discordoverlaylinux: filename=discordoverlaylinux-0.0.1-py3-none-any.whl size=17461 sha256=446a31a9b433e0ed76e41da21d3e806f54edc13138c8975a714ba323fb08a832
  Stored in directory: /tmp/pip-ephem-wheel-cache-569r8mhj/wheels/55/77/22/a5bc3392d5b09ee4e66fac207b732bc35871be1dcb959706cd
Successfully built discordoverlaylinux
ERROR: pyqtwebengine 5.15.0 has requirement PyQt5>=5.15, but you'll have pyqt5 5.14.1 which is incompatible.
Installing collected packages: PyQt5-sip, PyQtWebEngine, pyxdg, discordoverlaylinux
  WARNING: The script discord-overlay is installed in '/home/master/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed PyQt5-sip-12.8.0 PyQtWebEngine-5.15.0 discordoverlaylinux-0.0.1 pyxdg-0.26
</pre>

Second time I installed:
<pre>
$python -m pip install .
Processing /home/master/Programs/DiscordOverlayLinux
Requirement already satisfied: PyQt5 in /usr/lib/python3/dist-packages (from discordoverlaylinux==0.0.1) (5.14.1)
Requirement already satisfied: PyQt5-sip in /home/master/.local/lib/python3.8/site-packages (from discordoverlaylinux==0.0.1) (12.8.0)
Requirement already satisfied: PyQtWebEngine in /home/master/.local/lib/python3.8/site-packages (from discordoverlaylinux==0.0.1) (5.15.0)
Requirement already satisfied: pyxdg in /home/master/.local/lib/python3.8/site-packages (from discordoverlaylinux==0.0.1) (0.26)
Building wheels for collected packages: discordoverlaylinux
  Building wheel for discordoverlaylinux (setup.py) ... done
  Created wheel for discordoverlaylinux: filename=discordoverlaylinux-0.0.1-py3-none-any.whl size=17461 sha256=b9809e00384756d3f8c37336de7a9e9d7d1867af09f72cee375699a95f5e0d43
  Stored in directory: /tmp/pip-ephem-wheel-cache-m2z9xz_i/wheels/55/77/22/a5bc3392d5b09ee4e66fac207b732bc35871be1dcb959706cd
Successfully built discordoverlaylinux
Installing collected packages: discordoverlaylinux
  Attempting uninstall: discordoverlaylinux
    Found existing installation: discordoverlaylinux 0.0.1
    Uninstalling discordoverlaylinux-0.0.1:
      Successfully uninstalled discordoverlaylinux-0.0.1
  WARNING: The script discord-overlay is installed in '/home/master/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed discordoverlaylinux-0.0.1
</pre>

Let me know how else I can help.

**Comment by trigg** [comment]
This is appearing to creep in occasionally.

Would you please try `pip install PyQtWebEngine` and then attempt to run?

**Comment by dsk0** [comment]
That seems to have done it:
<pre>
$ python -m pip install PyQtWebEngine
Requirement already satisfied: PyQtWebEngine in ./.local/lib/python3.8/site-packages (5.15.0)
Collecting PyQt5>=5.15
  Downloading PyQt5-5.15.0-5.15.0-cp35.cp36.cp37.cp38-abi3-manylinux2014_x86_64.whl (76.6 MB)
     |████████████████████████████████| 76.6 MB 353 kB/s 
Requirement already satisfied: PyQt5-sip<13,>=12.8 in ./.local/lib/python3.8/site-packages (from PyQtWebEngine) (12.8.0)
Installing collected packages: PyQt5
Successfully installed PyQt5-5.15.0
</pre>

Works now, thanks and well done for making this useful tool :)

**Comment by trigg** [comment]
Thanks! Glad people are enjoying it. I keep meaning to put more into several featuers & bugs, but reality is conspiring against me
