### ISSUE TITLE
Cant open the Overlay

### ISSUE THREAD

**Issue by DexyStorm** [trigg/DiscordOverlayLinux#46]
Am on KDE. Distro is Arch.

./.local/bin/discord-overlay

returns

Traceback (most recent call last):
  File "./.local/bin/discord-overlay", line 33, in <module>
    sys.exit(load_entry_point('discordoverlaylinux==0.0.1', 'console_scripts', 'discord-overlay')())
  File "./.local/bin/discord-overlay", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dexy/.local/lib/python3.8/site-packages/discord_overlay/__init__.py", line 1, in <module>
    from .discord_overlay import *
  File "/home/dexy/.local/lib/python3.8/site-packages/discord_overlay/discord_overlay.py", line 21, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: /usr/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5

Am pretty new to Linux and this is my first bug report. Maybe I'm just doing something wrong.
Hardware: 2070super/R5 3600

**Comment by trigg** [comment]
No worries. What method did you use to install this?

Arch AUR is one option which *should* just work https://aur.archlinux.org/packages/discord-overlay-git/

**Comment by DexyStorm** [comment]
Hi. The first post was by following the installation guide from the README.

Now i tried it from the AUR and i couldn't even install it from the AUR. I got:

error: failed to commit transaction (conflicting files)
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/BaseDirectory.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/Config.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/DesktopEntry.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/Exceptions.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/IconTheme.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/IniFile.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/Locale.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/Menu.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/MenuEditor.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/Mime.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/RecentFiles.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__init__.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/BaseDirectory.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/Config.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/DesktopEntry.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/Exceptions.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/IconTheme.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/IniFile.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/Locale.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/Menu.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/MenuEditor.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/Mime.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/RecentFiles.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/__init__.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/util.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/util.py exists in filesystem
Errors occurred, no packages were upgraded.
error installing repo packages

**Comment by DexyStorm** [comment]
No my bad! I had some problems with python-pyxdg and it only showed me the problems now when i tried to do makepkg -si from the AUR.

python-pyxdg: /usr/lib/python3.8/site-packages/xdg/BaseDirectory.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/Config.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/DesktopEntry.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/Exceptions.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/IconTheme.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/IniFile.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/Locale.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/Menu.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/MenuEditor.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/Mime.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/RecentFiles.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__init__.py exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/BaseDirectory.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/Config.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/DesktopEntry.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/Exceptions.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/IconTheme.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/IniFile.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/Locale.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/Menu.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/MenuEditor.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/Mime.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/RecentFiles.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/__init__.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/__pycache__/util.cpython-38.pyc exists in filesystem
python-pyxdg: /usr/lib/python3.8/site-packages/xdg/util.py exists in filesystem
Errors occurred, no packages were upgraded.
error installing repo packages

I just removed them and now the overlay is working. Just need to figure out how it works exactly. Again, sorry my bad!
(Do i close this now?)
