### ISSUE TITLE
Compositing still enabled

### ISSUE THREAD

**Issue by BenjaminSchaaf** [trigg/DiscordOverlayLinux#47]
When playing a game in full-screen desktop environments like gnome disable compositing to significantly reduce input latency and allow for mixed refresh-rate setups to properly make use of a high refresh-rate monitor. When using this overlay compositing stays enabled in games like Team Fortress 2 causing a 60hz refresh rate and stuttering.

This is using X11. Unsure if this is fixable or not.

**Comment by trigg** [comment]
Hello! Compositing is the only method in X11 & Wayland that allows you to draw semi-transparent windows on top of other windows.

If your compositor is causing issues I advise finding one that works better for you. I personally use compton/picom. Compositors usually come with a lot of options which you can tweak to your liking.
