### ISSUE TITLE
Doesn't appear on KDE

### ISSUE THREAD

**Issue by LiamDawe** [trigg/DiscordOverlayLinux#48]
As of the newest version, the actual Overlay no longer appears on KDE Plasma. The UI app still works fine but obviously it's useless without the Overlay :P

It worked okay with the last version, when loading it gave what looked like a quick flash in the corner of my screen but then vanished. [This comment](https://www.reddit.com/r/linux_gaming/comments/i8o046/linux_discord_overlay_002/g19rv5e/) says they have their compositor disabled with the same issue, mine is enabled, so that's not the issue.

Only error in terminal is this:
`qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 721, resource id: 0, major code: 20 (GetProperty), minor code: 0`

**Comment by midget3111** [comment]
Thanks for the report! 
What distro are you running and I'll boot up and give it a test.

**Comment by LiamDawe** [comment]
Woops sorry, this is Manjaro KDE with NVIDIA GPU.

**Comment by midget3111** [comment]
Interestingly, I can't reproduce this. Installed discord on a fresh Manjaro KDE Plasma install, followed the steps in the readme using the latest source and it seems to work fine. Admittedly, I couldn't test with Nvidia GPU as I was using a VM. I assume you're using X11 rather than Wayland?

**Comment by LiamDawe** [comment]
This is X11 yes, so it might perhaps be NVIDIA specific?

**Comment by Findus23** [comment]
Just for reference, I am using Debian testing, an AMD GPU, X11 and plasmashell 5.17.5 and after the update everything still worked fine.

**Comment by midget3111** [comment]
> This is X11 yes, so it might perhaps be NVIDIA specific?

Just tried a fresh install on a machine with an Nvidia GPU. Worked as expected. 

How did you install? I had issues with pip so used the version from the AUR.

**Comment by LiamDawe** [comment]
Installed manually using the instructions.

I just tried the git version from AUR and not even a UI appears and all I see is this:

> [liam@liam-manjaro ~]$ discord-overlay
> 2020-08-19 16:19:18,250 DEBUG    Discovered screens: ['HDMI-0', 'DVI-D-0']
> 2020-08-19 16:19:18,250 DEBUG    Chose screen DVI-D-0
> qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 700, resource id: 0, major code: 20 (GetProperty), minor code: 0

UPDATE: scratch that, got confused. Same when installed from AUR, see the tray icon but the overlay is nowhere to be seen.

**Comment by UltraBlackLinux** [comment]
perfectly works for me though.
