### ISSUE TITLE
Overlay does not appear on GNOME 3

### ISSUE THREAD

**Issue by lugnutlarry** [trigg/DiscordOverlayLinux#51]
Running Pop!_OS 20.04 with GNOME 3 on an AMD GPU system. The software installed without a hitch and I am able to configure the overlay, but it does not appear anywhere on my screen. When I toggle 'Enable' on and off, I see a brief flicker in the shape of a rectangle in top left corner, where the overlay should be. 
I also have KDE Plasma installed on my pc, and the issue persists regardless of which DE I am using.

Sorry if this is a duplicate issue, first time using GitHub.

**Comment by trigg** [comment]
Apologies on the delay. Could I ask you to go back into the 'Layout' section again, wait for the page at the top to load, and re-select your options, and save again?

If this doesn't fix it please let me know

**Comment by lugnutlarry** [comment]
This mostly helped, in that the overlay is now showing in games / on desktop. However, there is now a black rectangular background behind the overlay.

https://imgur.com/a/pCq8OhM

**Comment by trigg** [comment]
This would happen if compositing is disabled. Not knowing Gnome well enough I'd say it's a setting but @midget3111 might have an answer

**Comment by lugnutlarry** [comment]
I don't know where compositor settings are on Gnome, but I was able to fix the issue by switching back over to KDE (i have both installed) and re-enabling the compositor there, which solved the problem for both desktop environments.
