### ISSUE TITLE
Manjaro KDE - overlay background not transparent

### ISSUE THREAD

**Issue by JonnyMuff** [trigg/DiscordOverlayLinux#56]
![Screenshot_20200920_133927](https://user-images.githubusercontent.com/68346834/93709520-6d1ba700-fb47-11ea-8ec2-f5bc905c132d.png)
Overlay itself seem to function normally, although it's not transparent at all with a huge black chunk on a screen

**Comment by trigg** [comment]
This leads me to believe your compositor is not active. Double check your window manager options or consider using picom if it's not part of your desktop environment

**Comment by JonnyMuff** [comment]
> This leads me to believe your compositor is not active. Double check your window manager options or consider using picom if it's not part of your desktop environment

you are absolutely right! apparently kwin compositor was disabled, switching to xrender fixed an issue
