### ISSUE TITLE
[Feature Request] Automatic Channel Selection

### ISSUE THREAD

**Issue by UltraBlackLinux** [trigg/DiscordOverlayLinux#57]
Hey there, 
Since Discord doesnt have overlay support for linux, It would be cool if this overlay had an auto choose option:
It shows the current Voice or Text channel you are in, without having to manually set it.

Thanks!

**Comment by trigg** [comment]
This is the end-goal of this software, and we're as close to that as we can be with the tools and expertise we have. We currently have no way of knowing what channels or server you have access to without the manual steps, and discord has no indication of what channels you are active in compared to simply having access to.

Patches are absolutely welcome

**Comment by UltraBlackLinux** [comment]
I dont know if anybody would use that - except from me - but create a better discord plugin that writes a file to tell the program in what channel you are.
I dont know js though

**Comment by midget3111** [comment]
Here you go - https://github.com/trigg/Discover

**Comment by UltraBlackLinux** [comment]
Thanks!
